In [1]:
import numpy as np

In [3]:
a = np.array([12, 23, 45, 67, 13])

In [5]:
a

array([12, 23, 45, 67, 13])

In [7]:
print(a)

[12 23 45 67 13]


In [9]:
type(a)

numpy.ndarray

In [13]:
a.size

5

In [15]:
a.dtype

dtype('int32')

In [17]:
a2 = np.array([12, 34, 55.11, True, "Shubham"])

In [19]:
a2

array(['12', '34', '55.11', 'True', 'Shubham'], dtype='<U32')

In [21]:
a2.dtype

dtype('<U32')

In [23]:
a2[4]

'Shubham'

In [25]:
a

array([12, 23, 45, 67, 13])

In [27]:
a * 2

array([ 24,  46,  90, 134,  26])

#### time difference between array and list

In [32]:
import time

In [40]:
time.time()   # time in seconds->> from 1970

1743919522.2032886

In [46]:
s = 1000000

list1 = list(range(s))
arr1 = np.array(list1)

In [48]:
# for list

strt_time = time.time()
x = [i * 2 for i in list1]
print(f"time taken by list is => {time.time() - strt_time}")

time taken by list is => 0.04520702362060547


In [50]:
# for array

strt_time = time.time()
a = arr1 * 2
print(f"time taken by array is => {time.time() - strt_time}")

time taken by array is => 0.0009968280792236328


In [52]:
# arange

In [54]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [58]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [60]:
np.arange(-5, 5, 0.25)

array([-5.  , -4.75, -4.5 , -4.25, -4.  , -3.75, -3.5 , -3.25, -3.  ,
       -2.75, -2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75,
       -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,
        1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,
        4.  ,  4.25,  4.5 ,  4.75])

In [62]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 2D arrays

In [67]:
arr = np.array([[1,2,3], [3,4,1], [3,5,10], [10,13,5]])

In [69]:
arr

array([[ 1,  2,  3],
       [ 3,  4,  1],
       [ 3,  5, 10],
       [10, 13,  5]])

In [71]:
arr.shape

(4, 3)

In [75]:
arr.size

12

In [77]:
arr.dtype

dtype('int32')

In [79]:
arr.ndim

2

In [83]:
arr.flatten()

array([ 1,  2,  3,  3,  4,  1,  3,  5, 10, 10, 13,  5])

In [85]:
arr.flatten().ndim

1

In [87]:
arr

array([[ 1,  2,  3],
       [ 3,  4,  1],
       [ 3,  5, 10],
       [10, 13,  5]])

In [89]:
arr.reshape(3, 4)

array([[ 1,  2,  3,  3],
       [ 4,  1,  3,  5],
       [10, 10, 13,  5]])

In [91]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  3],
       [ 4,  1],
       [ 3,  5],
       [10, 10],
       [13,  5]])

In [93]:
arr.reshape(2, -1)

array([[ 1,  2,  3,  3,  4,  1],
       [ 3,  5, 10, 10, 13,  5]])

In [95]:
arr.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  3]],

       [[ 4,  1],
        [ 3,  5]],

       [[10, 10],
        [13,  5]]])

In [97]:
arr.reshape(3, 2, 2).ndim

3

In [99]:
arr.reshape(4, 3, -1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 3],
        [ 4],
        [ 1]],

       [[ 3],
        [ 5],
        [10]],

       [[10],
        [13],
        [ 5]]])

In [103]:
a2

array(['12', '34', '55.11', 'True', 'Shubham'], dtype='<U32')

In [105]:
a2[4]

'Shubham'

In [107]:
a2[1:4]

array(['34', '55.11', 'True'], dtype='<U32')

In [109]:
arr

array([[ 1,  2,  3],
       [ 3,  4,  1],
       [ 3,  5, 10],
       [10, 13,  5]])

In [158]:
arr[1,1]

4

In [162]:
arr[0, :]

array([1, 2, 3])

In [111]:
arr[0:3, 0:2]

array([[1, 2],
       [3, 4],
       [3, 5]])

In [113]:
arr[1:3, 1:]

array([[ 4,  1],
       [ 5, 10]])

In [115]:
z = np.array([[2,2,2,4,5,6,6,12]])

In [119]:
np.unique(z)

array([ 2,  4,  5,  6, 12])

#### Linalg

In [122]:
a = np.array([[3,6], [4,8]])
b = np.array([[3, 5], [10, 1]])

In [124]:
a

array([[3, 6],
       [4, 8]])

In [126]:
b

array([[ 3,  5],
       [10,  1]])

In [128]:
# dot product
np.dot(a, b)

array([[69, 21],
       [92, 28]])

In [130]:
a @ b

array([[69, 21],
       [92, 28]])

In [132]:
"""
linear eq
1x + 3y = 10
3x + 4y = 12
""";

In [134]:
c = np.array([[1, 3], [3, 4]])
d = np.array([10, 12])

In [136]:
np.linalg.solve(c, d)

array([-0.8,  3.6])

In [138]:
np.subtract(a, b)

array([[ 0,  1],
       [-6,  7]])

In [140]:
np.linalg.det(a)

0.0

In [144]:
z = np.array([[1,2,3], [3,4,1], [3,5,10]])

In [146]:
np.linalg.inv(z)

array([[-3.5,  0.5,  1. ],
       [ 2.7, -0.1, -0.8],
       [-0.3, -0.1,  0.2]])

In [148]:
np.linalg.eig(z)

EigResult(eigenvalues=array([12.12877026, -0.26305401,  3.13428375]), eigenvectors=array([[-0.29076041, -0.81177703,  0.04379508],
       [-0.22180628,  0.58212816, -0.81659189],
       [-0.93073109, -0.0463127 ,  0.57555163]]))

In [150]:
# vector norm

vec = np.array([3, -4])

In [152]:
np.linalg.norm(vec)

5.0

In [156]:
help(np.linalg.norm)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix nor